// <auto-generated />
namespace Hogwarts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserAnswerState_AddColumn_Progress_UserderstandingLevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAnswerState_AddColumn_Progress_UserderstandingLevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803211432011_UserAnswerState_AddColumn_Progress_UserderstandingLevel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
