// <auto-generated />
namespace Hogwarts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ask_IsClosed_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ask_IsClosed_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201804220634554_Ask_IsClosed_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
